name: Run Phone Price Script

on:
  push:
    branches:
      - dev

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 undetected-chromedriver

      - name: Run phone price script
        run: python3 check-prices.py
