name: Fetch Phone Data

on:
  push:
    branches:
    - main
  
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch phone data with curl
        run: |
          curl -L -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "https://www.buybest.bg/manufacturers/google?category=1&per-page=24" -o phone_page.html
          
      - name: Run Python parsing script
        run: |
          python fetch_prices.py
